[package]
name = "libtokenizers"
version = "0.1.0"
authors = ["Marco Zocca"]
edition = "2021"

[lib]
crate-type = ["lib"]
path = "ffi.rs"

[dependencies]
tokenizers = { git = "https://github.com/huggingface/tokenizers" }